packages:
  - "packages/*"
  - "public/apps/*"

catalog:
  zod: "latest"
  drizzle-orm: "latest"

allowBuilds:
  '@clerk/shared': true
  esbuild: true

overrides:
  react: "19.2.8"
  react-dom: "19.2.8"
